### ISSUE TITLE
How to use klustair behing ingress using subpath /klustair?

### ISSUE THREAD

**Issue by hugodopradofernandes** [klustair/klustair-helm#26]
How to use klustair behing ingress using subpath /klustair?
The closest I got was this one, that returns unformated page and all links point to / not /klustair

![Screenshot_20210722_194455](https://user-images.githubusercontent.com/24471843/126718378-3c53f00b-a83c-49e4-81c8-20d7c148f823.png)

Ingress config:

```
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: ingress-klustair
  namespace: klustair-scan
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: klustair-app-frontend
            port:
              number: 80
        path: /klustair(/|$)(.*)
        pathType: Prefix

```
